import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle', timeout: 15000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: 'after-hero.png', scale: 'css' });
await page.evaluate(() => window.scrollTo(0, 1000));
await page.waitForTimeout(800);
await page.screenshot({ path: 'after-about.png', scale: 'css' });
await page.evaluate(() => window.scrollTo(0, 2200));
await page.waitForTimeout(800);
await page.screenshot({ path: 'after-programs.png', scale: 'css' });
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(800);
await page.screenshot({ path: 'after-footer.png', scale: 'css' });
await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(() => window.scrollTo(0, 0));
await page.waitForTimeout(800);
await page.screenshot({ path: 'after-mobile.png', scale: 'css' });
await browser.close();
console.log('done');
